name: test2.yml

on: 
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:
  ssc-ci-test:
    if: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Run SSC CI Test
        uses: fortify/github-action@feat/fcli-ci
        env:
          SSC_URL: ${{ vars.FH_DEMO_SSC_URL }}
          SSC_USER: ${{secrets.FH_DEMO_SSC_USER}}
          SSC_PASSWORD: ${{secrets.FH_DEMO_SSC_PWD}}
          SC_SAST_TOKEN: ${{secrets.FH_DEMO_SC_SAST_TOKEN}}
          SSC_APPVERSION: GitHub:EightBall
          SC_CLIENT_VERSION: 25.2
          SAST_SCAN_EXTRA_OPTS: --no-replace
