name: test2.yml

on: 
  workflow_dispatch:
  push:
    branches: [master]
    
jobs:
  ssc-ci-test:
    if: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            fcli_url: https://github.com/fortify/fcli/releases/download/dev_refactor.ci-rest-helpers/fcli-linux.tgz
          - os: windows-latest
            fcli_url: https://github.com/fortify/fcli/releases/download/dev_refactor.ci-rest-helpers/fcli-windows.zip
          - os: macos-latest
            fcli_url: https://github.com/fortify/fcli/releases/download/dev_refactor.ci-rest-helpers/fcli-mac.tgz
    runs-on: ${{ matrix.os }}
    steps:    
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Run SSC CI Test
        uses: fortify/github-action@feat/fcli-ci
        env:
          FCLI_URL: ${{ matrix.fcli_url }}
          SSC_URL: ${{ vars.FH_STAGE_SSC_URL }}
          SSC_USER: ${{secrets.FH_STAGE_SSC_USER}}
          SSC_PASSWORD: ${{secrets.FH_STAGE_SSC_PWD}}
          SC_SAST_TOKEN: ${{secrets.FH_STAGE_SC_SAST_TOKEN}}
          SSC_APPVERSION: GitHub:EightBall
          SC_CLIENT_VERSION: 25.4
          SAST_SCAN_EXTRA_OPTS: --no-replace
          SAST_EXPORT_EXTRA_OPTS: --publish
          DEBRICKED_EXPORT_EXTRA_OPTS: --publish
